Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/04/2022
Var
// Seção de Declarações das variáveis 
x: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
x <- 0
para x de 1 ate 9 faca
 x <- x + 1
 escreval(x)
fimpara

Fimalgoritmo