Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/03/2022
Var
// Seção de Declarações das variáveis 
resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
resultado <- (((2/3)-(5-3))+1)*5
escreval("Resultado:", resultado)

Fimalgoritmo